import { contextBridge, ipcRenderer } from 'electron';
import type { Mode } from '../shared/contracts';
import type { SimForgeDesktopApi } from '../shared/desktop-api';

const api: SimForgeDesktopApi = {
  getState: () => ipcRenderer.invoke('state:get'),
  setMode: (mode: Mode) => ipcRenderer.invoke('mode:set', mode),
  refreshScene: () => ipcRenderer.invoke('scene:refresh'),
  getLatestValidation: () => ipcRenderer.invoke('validation:get-latest'),
  runValidation: () => ipcRenderer.invoke('validation:run'),
  applyValidationFix: (input) => ipcRenderer.invoke('validation:apply-fix', input),
  undoLatestValidationFix: () => ipcRenderer.invoke('validation:undo-latest-fix'),
  listCheckpoints: () => ipcRenderer.invoke('checkpoint:list'),
  approveCheckpointRestore: (checkpointId, planHash) =>
    ipcRenderer.invoke('checkpoint:approve-restore', checkpointId, planHash),
  restoreCheckpoint: (checkpointId, planHash, approvalId) =>
    ipcRenderer.invoke('checkpoint:restore', checkpointId, planHash, approvalId),
  getPrimitiveRobotProposal: () => ipcRenderer.invoke('robot:proposal-primitive'),
  buildPrimitiveRobot: (approvalId) => ipcRenderer.invoke('robot:build-primitive', approvalId),
  getWarehouseProposal: () => ipcRenderer.invoke('scene:proposal-warehouse'),
  buildWarehouseScene: (approvalId) => ipcRenderer.invoke('scene:build-warehouse', approvalId),
  getLatestImportReport: () => ipcRenderer.invoke('import:get-latest'),
  stageBundledRobotImport: () => ipcRenderer.invoke('import:stage-bundled-robot'),
  getImportedRobotProposal: () => ipcRenderer.invoke('import:proposal-robot'),
  buildImportedRobot: (approvalId) => ipcRenderer.invoke('import:build-robot', approvalId),
  getImportedRobotModificationProposal: () => ipcRenderer.invoke('import:proposal-modification'),
  modifyImportedRobot: (approvalId) => ipcRenderer.invoke('import:modify-robot', approvalId),
  listNativeImports: () => ipcRenderer.invoke('import:list-native'),
  chooseNativeImport: () => ipcRenderer.invoke('import:choose-native'),
  executeNativeImport: (proposal, approvalId) => ipcRenderer.invoke('import:execute-native', proposal, approvalId),
  getNativeImportDecisionProposal: (importId, accept) => ipcRenderer.invoke('import:decision-proposal', importId, accept),
  executeNativeImportDecision: (proposal, approvalId) => ipcRenderer.invoke('import:execute-decision', proposal, approvalId),
  renderPrimitiveRobotReview: (label) => ipcRenderer.invoke('robot:render-review', label),
  listReviews: () => ipcRenderer.invoke('review:list'),
  getReviewImage: (reviewId, view) => ipcRenderer.invoke('review:image', reviewId, view),
  chooseExportDestination: (kind) => ipcRenderer.invoke('export:choose-destination', kind),
  proposeExport: (kind, destination, overwrite) => ipcRenderer.invoke('export:propose', kind, destination, overwrite),
  executeExport: (proposal, approvalId) => ipcRenderer.invoke('export:execute', proposal, approvalId),
  listExports: () => ipcRenderer.invoke('export:list'),
  getIsaacEnvironment: () => ipcRenderer.invoke('isaac:environment'),
  getIsaacExperimentProposal: () => ipcRenderer.invoke('isaac:proposal'),
  runIsaacExperiment: (proposal, approvalId) => ipcRenderer.invoke('isaac:run', proposal, approvalId),
  listIsaacExperiments: () => ipcRenderer.invoke('isaac:list'),
  getIsaacExperimentImage: (experimentId) => ipcRenderer.invoke('isaac:image', experimentId),
  getIsaacExperimentImages: (experimentId) => ipcRenderer.invoke('isaac:images', experimentId),
  openIsaacExperiment: (experimentId) => ipcRenderer.invoke('isaac:open', experimentId),
  analyzeIsaacExperiment: (experimentId) => ipcRenderer.invoke('isaac:analyze', experimentId),
  getIsaacCorrectionProposal: (experimentId) => ipcRenderer.invoke('isaac:correction-proposal', experimentId),
  applyIsaacCorrection: (proposal, approvalId) => ipcRenderer.invoke('isaac:correction-apply', proposal, approvalId),
  executeTool: (input) => ipcRenderer.invoke('tool:execute', input),
  approveAction: (input) => ipcRenderer.invoke('approval:create', input),
  createGoal: (input) => ipcRenderer.invoke('job:create', input),
  approveGoal: (jobId, planHash) => ipcRenderer.invoke('job:approve', jobId, planHash),
  commandGoal: (jobId, command, taskIndex) =>
    ipcRenderer.invoke('job:command', jobId, command, taskIndex),
  getGoal: (jobId) => ipcRenderer.invoke('job:get', jobId),
  runNextGoalTask: (jobId) => ipcRenderer.invoke('job:run-next', jobId),
  providerStatus: (providerId) => ipcRenderer.invoke('provider:status', providerId),
  configureProvider: (providerId, credential) =>
    ipcRenderer.invoke('provider:credential-set', providerId, credential),
  removeProvider: (providerId) => ipcRenderer.invoke('provider:credential-remove', providerId),
  discoverProviderModels: (providerId) => ipcRenderer.invoke('provider:discover', providerId),
  probeProvider: (providerId, modelId) => ipcRenderer.invoke('provider:probe', providerId, modelId),
  probeMockProvider: () => ipcRenderer.invoke('provider:probe-mock'),
  runMockThinSlice: (prompt) => ipcRenderer.invoke('provider:run-mock-slice', prompt),
  listConversations: (search) => ipcRenderer.invoke('conversation:list', search),
  createConversation: (title) => ipcRenderer.invoke('conversation:create', title),
  renameConversation: (conversationId, title) => ipcRenderer.invoke('conversation:rename', conversationId, title),
  deleteConversation: (conversationId) => ipcRenderer.invoke('conversation:delete', conversationId),
  branchConversation: (conversationId, throughMessageId) => ipcRenderer.invoke('conversation:branch', conversationId, throughMessageId),
  getChat: (conversationId) => ipcRenderer.invoke('conversation:get', conversationId),
  sendChat: (conversationId, message, attachmentIds) => ipcRenderer.invoke('conversation:send', conversationId, message, attachmentIds),
  stopChat: (conversationId) => ipcRenderer.invoke('conversation:stop', conversationId),
  compactConversation: (conversationId) => ipcRenderer.invoke('conversation:compact', conversationId),
  getConversationContext: (conversationId) => ipcRenderer.invoke('conversation:context', conversationId),
  chooseAttachments: (conversationId) => ipcRenderer.invoke('attachment:choose', conversationId),
  listAttachments: (conversationId) => ipcRenderer.invoke('attachment:list', conversationId),
  getWorkspaceSettings: () => ipcRenderer.invoke('workspace:settings-get'),
  updateWorkspaceSettings: (settings) => ipcRenderer.invoke('workspace:settings-update', settings),
  listMemories: (scope) => ipcRenderer.invoke('memory:list', scope),
  saveMemory: (scope, title, content, id) => ipcRenderer.invoke('memory:save', scope, title, content, id),
  deleteMemory: (scope, id) => ipcRenderer.invoke('memory:delete', scope, id),
  exportMemories: (scope) => ipcRenderer.invoke('memory:export', scope),
  getUsageSummary: () => ipcRenderer.invoke('usage:summary'),
  exportProjectData: () => ipcRenderer.invoke('project:export-data'),
  exportDiagnostics: () => ipcRenderer.invoke('diagnostics:export'),
  deleteCurrentProject: (confirmation) => ipcRenderer.invoke('project:delete-current', confirmation),
  generateScenePreview: () => ipcRenderer.invoke('preview:generate'),
  getScenePreviewData: (previewId) => ipcRenderer.invoke('preview:data', previewId),
  selectSceneObject: (previewId, objectId) => ipcRenderer.invoke('preview:select-object', previewId, objectId),
  openSceneInBlender: () => ipcRenderer.invoke('scene:open-in-blender'),
  listVersions: () => ipcRenderer.invoke('version:list'),
  createVersion: (name, checkpointId, branchOf) => ipcRenderer.invoke('version:create', name, checkpointId, branchOf),
  getTimeline: () => ipcRenderer.invoke('timeline:list'),
  runEnvironmentDoctor: () => ipcRenderer.invoke('doctor:run'),
};

contextBridge.exposeInMainWorld('simforge', api);
